[package]
name = "xm-blackhole"
version = "0.1.0"
edition = "2021"
description = "极具视觉冲击力与直觉交互的桌面暗黑黑洞引擎"

[lib]
name = "xm_blackhole_lib"
crate-type = ["staticlib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri-plugin-process = { workspace = true }
tauri-plugin-updater = { workspace = true }
# 星码行空共享
xm-core = { path = "../../../packages/rust/xm-core" }

# Tauri
tauri = { version = "2.3", features = ["tray-icon"] }
tauri-plugin-single-instance = "2"

serde = { version = "1", features = ["derive"] }
serde_json = "1"
log = "0.4"
base64 = "0.22"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_UI_WindowsAndMessaging",
] }

[features]
default = []
xm-f12 = ["xm-core/xm-f12", "tauri/devtools"]
